project:
  type: website
  output-dir: docs

website:
  title: "Max Grezlik"
  site-url: https://maxgrezlik.github.io
  repo-url: https://github.com/MaxGrezlik/MaxGrezlik.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/MaxGrezlik
        aria-label: GitHub

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true

editor: visual
