project:
  type: website
  output-dir: docs

website:
  title: "Max Grezlik"
  site-url: https://maxgrezlik.github.io
  repo-url: https://github.com/MaxGrezlik/MaxGrezlik.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        aria-label: GitHub
        menu:
          - text: Work (MGrezlik)
            href: https://github.com/MGrezlik
          - text: Personal (MaxGrezlik)
            href: https://github.com/MaxGrezlik

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true

editor: visual
